// Map Enka API property keys to SDK stat names
export const ENKA_PROPERTY_MAP: Record<string, string> = {
  "HPBase": "baseHp",
  "HPDelta": "flatHp",
  "HPAddedRatio": "percentHp",
  "AttackBase": "baseAtk",
  "AttackDelta": "flatAtk",
  "AttackAddedRatio": "percentAtk",
  "DefenceBase": "baseDef",
  "DefenceDelta": "flatDef",
  "DefenceAddedRatio": "percentDef",
  "SpeedBase": "baseSpeed",
  "SpeedDelta": "flatSpeed",
  "SpeedAddedRatio": "percentSpeed",
  "CriticalChanceBase": "critRate",
  "CriticalDamageBase": "critDmg",
  "StatusProbabilityBase": "effectHit",
  "StatusResistanceBase": "effectRes",
  "BreakDamageAddedRatioBase": "breakEffect",
  "SPRatioBase": "energyRecovery",
  "PhysicalAddedRatio": "physicalDmgBoost",
  "FireAddedRatio": "fireDmgBoost",
  "IceAddedRatio": "iceDmgBoost",
  "ThunderAddedRatio": "lightningDmgBoost",
  "WindAddedRatio": "windDmgBoost",
  "QuantumAddedRatio": "quantumDmgBoost",
  "ImaginaryAddedRatio": "imaginaryDmgBoost",
  "AllDamageTypeAddedRatio": "allDmgBoost"
};
