/**
 * Calculates energy gained from a single action.
 * @param baseEnergy - Base energy generated by the action.
 * @param errPercent - Energy Regeneration Rate as a decimal (e.g. 0.194 for 19.4%).
 */
export function calculateEnergyGain(baseEnergy: number, errPercent: number): number {
  return baseEnergy * (1 + errPercent);
}

/**
 * Checks whether a sequence of actions generates enough energy to cast ultimate.
 * @param actions - Array of actions, each with a `baseEnergy` value.
 * @param maxEnergy - Energy cost of the ultimate.
 * @param errPercent - Energy Regeneration Rate as a decimal.
 * @param flatEnergyBonus - Flat energy bonus (e.g. from rope). Defaults to 0.
 */
export function canReachUltimate(
  actions: Array<{ baseEnergy: number }>,
  maxEnergy: number,
  errPercent: number,
  flatEnergyBonus: number = 0
): boolean {
  let totalEnergy = flatEnergyBonus;
  for (const action of actions) {
    totalEnergy += calculateEnergyGain(action.baseEnergy, errPercent);
  }
  return totalEnergy >= maxEnergy;
}
